### PR TITLE
Fix for JavaScript module path to handle app not being hosted at the root of the website

### LINKED ISSUE #2: Error when using a Wasm App that is served from a different path than the root of the website
First, Nice Lib, congrats

When used with a diff base address, request for Blazor.BroadcastChannel.js file fail with 404 http status code.

i Found this

https://github.com/dotnet/aspnetcore/issues/47627

### PR DESCRIPTION
**Pull request by victorperez2911**
…rent from the WebSite Root (e.g. using the href attribute element of the index.html base element)

### CODE REVIEW

File: src/Blazor.BroadcastChannel/BroadcastChannelService.cs [hunk 1]
```diff
@@ -1,14 +1,19 @@
...
 namespace Blazor.BroadcastChannel
 {
     internal class BroadcastChannelService : IBroadcastChannelService
     {
         private readonly Lazy<ValueTask<IJSObjectReference>> _moduleTask;
 
-        public BroadcastChannelService(IJSRuntime jsRuntime)
+        public BroadcastChannelService(IJSRuntime jsRuntime, NavigationManager NavManager)
         {
-            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
```
Comment (tpeczek) [inline src/Blazor.BroadcastChannel/BroadcastChannelService.cs:11]: I've done some testing and it looks that it might be enough to change the path to `"./_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"`. That said, I don't know if I have reproduced your scenario, can you test that approach?

File: src/Blazor.BroadcastChannel/BroadcastChannelService.cs [hunk 2]
```diff
@@ -1,14 +1,19 @@
...
+
+            string path = new Uri(NavManager.BaseUri).AbsolutePath + "_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js";
+
+            //_moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
```
Comment (tpeczek) [inline src/Blazor.BroadcastChannel/BroadcastChannelService.cs]: No need to comment out the code, you can just delete it 😉.

**Review by tpeczek — CHANGES_REQUESTED** [review]

File: src/Blazor.BroadcastChannel/BroadcastChannelService.cs (hunk 1 above)
Comment (victorperez2911) [reply src/Blazor.BroadcastChannel/BroadcastChannelService.cs:11]: The scenario I brought up only occurs after deployment, which makes testing your approach difficult.

Can you publish a pre-release of the package with this change?

Comment (tpeczek) [reply src/Blazor.BroadcastChannel/BroadcastChannelService.cs:11]: Sure thing, but it may need to wait till weekend.

**Review by tpeczek — APPROVED** [review]
